{"uuid": "41e31735-c064-4557-b1dc-4f5e4076056c", "children": ["cb81c443-f06c-4f4b-9a0c-da4f91d1a638"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <b> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed\n\n", "trace": "  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Aleksandr\\project\\conftest.py\", line 33, in app\n    fixture.session.ensure_login(username=web_config[\"username\"], password=web_config[\"password\"])\n  File \"C:\\Users\\Aleksandr\\project\\fixture\\session.py\", line 45, in ensure_login\n    if self.is_logged_in_as(username):\n  File \"C:\\Users\\Aleksandr\\project\\fixture\\session.py\", line 36, in is_logged_in_as\n    return self.get_logged_user() == username\n  File \"C:\\Users\\Aleksandr\\project\\fixture\\session.py\", line 40, in get_logged_user\n    return wd.find_element_by_xpath(\"//div/div[1]/form/b\").text[1:-1]\n  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 76, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)['value']\n  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 628, in _execute\n    return self._parent.execute(command, params)\n  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Aleksandr\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1632511064595, "stop": 1632511065740}], "start": 1632511064595, "stop": 1632511066094}